"""Local helpers for the UMAR quantile reproduction workflow."""

from .umar_utils import (
    MODEL_DISPLAY_NAMES,
    MODEL_LITERATURE_FAMILIES,
    MODEL_PAPER_ALIGNMENT,
    ResidualBootstrapEmulator,
    add_model_annotations,
    build_asymptotic_quantile_curves,
    empirical_quantile_curve,
    gamma_schedule_power,
    literature_model_family,
    literature_model_name,
    literature_model_note,
    make_default_emulators,
    pseudo_delta_lower_bounded,
    pseudo_delta_lower_variance,
    pseudo_delta_upper_bounded,
    pseudo_delta_upper_variance,
    rmse_score,
    summarize_series,
    variance_ci_bootstrap,
    wasserstein_1d_empirical,
    w1_confidence_radius_subgaussian,
    w1_pseudo_discrepancy_ball,
)

__all__ = [
    "MODEL_DISPLAY_NAMES",
    "MODEL_LITERATURE_FAMILIES",
    "MODEL_PAPER_ALIGNMENT",
    "ResidualBootstrapEmulator",
    "add_model_annotations",
    "build_asymptotic_quantile_curves",
    "empirical_quantile_curve",
    "gamma_schedule_power",
    "literature_model_family",
    "literature_model_name",
    "literature_model_note",
    "make_default_emulators",
    "pseudo_delta_lower_bounded",
    "pseudo_delta_lower_variance",
    "pseudo_delta_upper_bounded",
    "pseudo_delta_upper_variance",
    "rmse_score",
    "summarize_series",
    "variance_ci_bootstrap",
    "wasserstein_1d_empirical",
    "w1_confidence_radius_subgaussian",
    "w1_pseudo_discrepancy_ball",
]
